name: craft_launcher
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.karasu256.com

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
